shim-version: v0.1.9@sha256:410510c9e8e4c7489dd201fede302dee8455075ca28f4f0abbf84bded943b8f1
cvm-version: 0.1.3
ovmf-version: 0.0.2
cpus: 16
memory: 65536

models:
  - name: "mistral-small-3-1-24b"
    repo: "mistralai/Mistral-Small-3.1-24B-Instruct-2503@4b8dd8aae705887db5295fcbff4aedbb92d682eb"
    mpk: "23cd0af7cb8f25d98be62011728497ffddcbefca748fe273c36bb823fd7bf95f_96077783040_e60a5d74-a8de-56df-a0b3-00f55e7a0d47"
vllm-args: --tool-call-parser mistral --enable-auto-tool-choice --chat-template /etc/tinfoil/templates/tool_chat_template_mistral3.jinja --gpu-memory-utilization 0.95 --limit_mm_per_prompt image=10

shim:
  listen-port: 443
  upstream-port: 8080
  control-plane: https://api.tinfoil.sh
  publish-attestation: false
  tls-challenge: dns
  paths:
    - /v1/chat/completions
    - /metrics
